### ISSUE TITLE
what allocation mode does the sajson benchmark use?

### ISSUE THREAD

**Issue by chadaustin** [project-gemmi/benchmarking-json#1]
Cool!  Thanks for running these benchmarks.  Always interesting.

Out of curiosity, is the benchmark using the single allocation memory allocation mode or the dynamic allocation mode?  The latter trades a bit of CPU performance for much lower peak memory usage when parsing.

**Comment by wojdyr** [comment]
Whatever nativejson-benchmark is using.
Looking at it, it's dynamic allocation
https://github.com/miloyip/nativejson-benchmark/blob/master/src/tests/sajsontest.cpp#L80
